version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - laravel

  mariadb:
    image: mariadb:10.4.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: UrXc3whE2q2U5MZf
      MYSQL_DATABASE: laravel
    volumes:
      - ./db/:/var/lib/mysql/
    networks:
      - laravel

  php:
    image: masumonline/php-fpm7.4
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
        - laravel

  artisan:
    image: masumonline/php-fpm7.4
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel
  
  adminer:
    image: michalhosna/adminer
    restart: always
    ports:
      - 8077:8080
    environment:
      ADMINER_PASSWORD: UrXc3whE2q2U5MZf
      ADMINER_SERVER: mariadb
      ADMINER_USERNAME: root
    networks:
          - laravel

    
